-- Your SQL goes here

CREATE TABLE contests(
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    num_problems INT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    creator_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);




CREATE OR REPLACE FUNCTION UPDATE_ROW_UPDATED_AT() RETURNS TRIGGER AS $$
BEGIN
	NEW.updated_at = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;


CREATE TRIGGER SET_UPDATED_AT_ON_CONTESTS
BEFORE
UPDATE ON CONTESTS
FOR EACH ROW EXECUTE FUNCTION UPDATE_ROW_UPDATED_AT();