
CREATE TABLE problems(
id VARCHAR(255) PRIMARY KEY,
name VARCHAR(255) NOT NULL,
num_tests INT NOT NULL,
contest_id VARCHAR(255) NOT NULL REFERENCES contests(id) ON DELETE CASCADE ON UPDATE CASCADE
);