-- Your SQL goes here
CREATE TABLE submissions (
    id SERIAL PRIMARY KEY,
    code VARCHAR(6000) NOT NULL,
    extension VARCHAR(20) NOT NULL,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    problem_id INT NOT NULL REFERENCES problems(id) ON DELETE CASCADE ON UPDATE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verdict VARCHAR(255) NOT NULL DEFAULT 'pending'
);